---
path:
    blob_base_dir: /
    data: pepsi-plano-biscuits/data/
    images: images
    raw: pepsi-plano-biscuits/data/raw
    annotations: annotations_master
    raw_annotations: pepsi-plano-biscuits/data/raw/annotations_master
    classes: pepsi-plano-biscuits/data/lookups/predefined_classes.txt
    non_packet: pepsi-plano-biscuits/data/lookups/non_packets.txt
    project: /
    packets_lookup: 'lookups/packets_lookup.csv'
    rackrow_lookup: 'lookups/rackrow_lookup.csv'
    validation_images: ''
    remove_images_json: 'pepsi-plano-biscuits/data/output/remove_images/remove_images'


data_path: 
    blob_base_dir: / 
    images_dir: pepsi-plano-biscuits/data/all_images_staging_test # folder for incremental images (need to check the input data stream in production)
    output_images_folder: op_annotations/ # sub-folder under which annotations would be stored (to be automated later on)
    refrained_images_file: pepsi-plano-biscuits/data/output/remove_images/remove_images_08_12_2021.json # folder for refrained images


yolov5_detect_packets:
  model_version: 'medium'
  weights_small: 'pepsi-plano-biscuits/data/model/detetction_weights/packets/small_best.pt'
  #weights_medium: '/pepsi-plano-biscuits/runs/packets/train/new_main_exp_all_medium/weights/best.pt'   #model.pt path(s)
  weights_medium: 'pepsi-plano-biscuits/data/model/detetction_weights/packets/medium_best.pt'
  imgsz: [640]
  conf_thres: 0.4  #object confidence threshold
  iou_thres: 0.5  #IOU threshold for NMS
  max_det: 1000  # maximum detections per image
  device: ''  # cuda device, i.e. 0 or 0,1,2,3 or cpu
  view_img: False  # show results
  save_txt: False  # save results to *.txt
  save_conf: False  # save confidences in --save-txt labels
  save_crop: False  # save cropped prediction boxes
  nosave: True  # do not save images/videos
  classes:  # filter by class: --class 0, or --class 0 2 3
  agnostic_nms: False  # class-agnostic NMS
  augment: False  # augmented inference
  visualize: False  # visualize features
  update: False  # update all models
  project: 'runs/packets/detect'  # save results to project/name
  name: 'new_main_exp_all_medium'  # save results to project/name
  exist_ok: False  # existing project/name ok, do not increment
  line_thickness: 3  # bounding box thickness (pixels)
  hide_labels: True  # hide labels
  hide_conf: False  # hide confidences
  half: False  # use FP16 half-precision inference

yolov5_detect_rackrow:
  model_version: 'small'
  #weights_small: '/pepsi-plano-biscuits/runs/new_rackrow/train/main_exp_all2/weights/best.pt'   #model.pt path(s)
  weights_small: 'pepsi-plano-biscuits/data/model/detetction_weights/rackrow/small_best.pt'
  weights_medium: ''
  imgsz: [640]
  conf_thres: 0.50  #object confidence threshold
  iou_thres: 0.45  #IOU threshold for NMS
  max_det: 300  # maximum detections per image
  device: ''  # cuda device, i.e. 0 or 0,1,2,3 or cpu
  view_img: False  # show results
  save_txt: False  # save results to *.txt
  save_conf: False  # save confidences in --save-txt labels
  save_crop: False  # save cropped prediction boxes
  nosave: True  # do not save images/videos
  classes:  # filter by class: --class 0, or --class 0 2 3
  agnostic_nms: False  # class-agnostic NMS
  augment: False  # augmented inference
  visualize: False  # visualize features
  update: False  # update all models
  project: 'runs/new_rackrow/detect'  # save results to project/name
  name: 'exp_all'  # save results to project/name
  exist_ok: False  # existing project/name ok, do not increment
  line_thickness: 3  # bounding box thickness (pixels)
  hide_labels: False  # hide labels
  hide_conf: False  # hide confidences
  half: False  # use FP16 half-precision inference

# mlflow_logging: 
#     artifacts_location: file:///pepsi-plano-biscuits/model_tracking/artifacts
#     uri_train_valid: file:///pepsi-plano-biscuits/model_tracking/experiments
#     port: 5050
#     host: localhost
#     temp_artifacts_location: /pepsi-plano-biscuits/model_tracking/artifacts_temp

packets_detection:
    output_dir: pepsi-plano-biscuits/data/output/image_annotations/packets_detection/  # save json files

rackrow_detection:
    output_dir: pepsi-plano-biscuits/data/output/image_annotations/rackrow_detection/  # save json files

sub_brand_detection:
    model_dir: pepsi-plano-biscuits/data/model/sub_brand_classification_weights/1130_InceptionResNetV2_0.0002LR_100Epoch_46Classes/
    input_json: pepsi-plano-biscuits/data/output/image_annotations/packets_detection/  # output from the packet detection model in json format
    cropped_size: 128  # to be used same as was used in training (would be automated in next iterations)
    output_dir: pepsi-plano-biscuits/data/output/image_annotations/sub_brand_detection/

integrated_output:
    packets_output_dir: pepsi-plano-biscuits/data/output/image_annotations/packets_detection/
    rackrow_output_dir: pepsi-plano-biscuits/data/output/image_annotations/rackrow_detection/
    sub_brand_output_dir: pepsi-plano-biscuits/data/output/image_annotations/sub_brand_detection/
    integrated_dir: pepsi-plano-biscuits/data/output/image_annotations/integrated/

compliance:
    path:
        image_output: data/output/image_annotations/test_outputs
        output: data/output/compliance/location_pickles/test_loader
        output_prev_after_comparsion: pepsi-plano-biscuits/data/output/compliance/prev_after_new_best/
    threshold:
        packet_row_overlap_thresh: 0.7
        packet_top_row_overlap_thresh: 0.5
        missing_row_thresh: 0.8
        missing_top_row_packet_overlap_thresh: 0.7
        top_row_additional_pixels: 25
        top_row_additional_thresh_pixels: 50
        empty_row_bbox_thresh: 0.5
        blank_middle_bbox_thresh: 0.5
        blank_start_bbox_thresh: 0.5
        blank_end_bbox_thresh: 0.5
        blank_predicted_overlap_iou: 0.5 
        missing_mid_row_thresh: 2.2

image_check:
    total_detection_threshold: 0.5
    rack_area_threshold: 65
    packets_area_threshold: 85
    row_count_threshold: 1

consolidated_path:
    template_images: pepsi-plano-biscuits/data/vendor_samples/images_consolidated/
    template_csvs: pepsi-plano-biscuits/data/output/image_annotations/consolidated/
